### ISSUE TITLE
Deleting an application to a Student Session crashes the web application.

### ISSUE THREAD

**Issue by AstonAkerman** [careerfairsystems/nexpo-web#3]
To recreate:
1.Login as student
2.Go to Student Session Applications (Student Session in menu -> View Applications)
3.If the user has no current applications then apply to a company.
4.Attempting to delete an application successfully removes applications from the list upon refreshing the page, but crashes the web page.

![StudentSessionIssue_screenshot_1](https://user-images.githubusercontent.com/65492998/87855461-d4836380-c918-11ea-8f92-193032e1ff79.png)

After deleting the application to Spotify a blank page with these messages is shown:

![StudentSessionIssue_screenshot_2](https://user-images.githubusercontent.com/65492998/87855462-d51bfa00-c918-11ea-9bb2-a49e9366a201.png)

Half a second later the web page crashes and this error message is received.

![StudentSessionIssue_screenshot_crash](https://user-images.githubusercontent.com/65492998/87855463-d5b49080-c918-11ea-9e55-76de9fb3a6c3.png)

Upon refreshing the page the application has succesfully been deleted.

![StudentSessionIssue_screenshot_refresh](https://user-images.githubusercontent.com/65492998/87855464-d5b49080-c918-11ea-948d-b28b7372b47c.png)

**Comment by AstonAkerman** [comment]
Backend terminal response:

![StudentSessionIssue_screenshot_crash_terminal](https://user-images.githubusercontent.com/65492998/87855905-b10de800-c91b-11ea-93c4-ba46b40ba796.png)

**Comment by adriangoransson** [comment]
Something is off with the schema generation.
https://github.com/careerfairsystems/nexpo-web/blob/master/src/Store/normalizr/schema.js#L160

My guess is that each `studentSessionApplication` is being matched with `company` and after removing an application there are N companies but N-1 applications. The "hole" is transformed into an `undefined` element of the array.
