### ISSUE TITLE
Company cannot change existing rating of student

### ISSUE THREAD

**Issue by AstonAkerman** [careerfairsystems/nexpo-web#6]
To recreate:
1.Login as a company with an existing application and rating from a student.
2.Change or reset the rating.

Existing rating

![Company_cannot_change_score](https://user-images.githubusercontent.com/65492998/87856381-1f07de80-c91f-11ea-9732-7745e547f66c.png)

Screenshot is taken as I attempt to change the rating in order for the "Your Application could not be saved." notification to be caught on the screenshot, the mouse is hovering over 1/5 stars as that is what I attempted to change the rating to. But after unhovering the rating is returned to the intial rating of 4/5 stars.

![Company_cannot_change_score2](https://user-images.githubusercontent.com/65492998/87856379-1f07de80-c91f-11ea-8fbd-6931a4bdaa18.png)

Backend terminal response

![Company_cannot_change_score3](https://user-images.githubusercontent.com/65492998/87856378-1e6f4800-c91f-11ea-8a49-fe8a244805f6.png)

**Comment by emarforio** [comment]
Now tracked in #144
